#include "../include/icon_parse.h"
#include "../include/shared.h"
#include <wchar.h>
#include <string.h>

// HashMapElement defaults[] = {
//   {T_DIR, L'\U0001f4c2'},

//   {T_FILE, L'\U0001f4c4'},
//   {T_PIPE, L'\U0001f4e9'},
//   {T_SOCKET, L'\U0001f4ec'},
//   {T_EXE, L'\U0001f3d7'},
//   {T_DIR_LINK, L'\U0001f5c2'},
//   {T_FILE_LINK, L'\U0001f516'},
//   {T_DEVICE_CHAR, L'\U0001f5a8'},
//   {T_DEVICE_BLOCK, L'\U0001f4bd'},
//   {T_SPECIAL, L'\U0001f4df'},
//   {NULL, NULL}
// };




char* getFileName(char path[]) {
    int last = 0;
    
    for (int i = 0; i < 255 && path[i] != '\0'; i++) {
        if (path[i] == '/') {
            last = i + 1; 
        }
    }

    // Restituisci il puntatore all'ultimo nome del file
    return &path[last];
}



// Funzione per ottenere l'icona in base all'estensione
wchar_t get_icon_for_extension(char *extension) {
  
    for (int i = 0; icons_by_extension[i].key != NULL; i++) {
        if (strcmp(icons_by_extension[i].key, extension) == 0) {
            return icons_by_extension[i].icon;
        }
    }
    return L'\U0001f4c4'; // Icona predefinita per file sconosciuto
}

// Funzione per ottenere l'icona in base al nome
wchar_t get_icon_for_name(char *filename) {  
    
    for (int i = 0; icons_by_name[i].key != NULL; i++) {
        if (strcmp(icons_by_name[i].key, filename) == 0) {
            return icons_by_name[i].icon;
        }
    }
    return L'\U0001f4c2';
}

// Funzione principale per ottenere l'icona per un path
wchar_t get_icon_for_path(Node *node) {
    // Estrae l'estensione
    char *extension = strrchr(getFileName(node->name), '.');
    
    // Estrae il nome del file
    char *filename = getFileName(node->name);
    // filename = (filename != NULL) ? filename + 1 : path;

    // Controlla il nome specifico
    // const char *icon = get_icon_for_name(filename);
    // if (icon != NULL) {
        // return icon;
    // }

    // Controlla l'estensione se il nome non ha corrispondenza
    if (extension != NULL) {
        return get_icon_for_extension(extension);
    }

    // return "📁"; // Icona predefinita se non c'è una corrispondenza
}





/*
HashMapElement* get_default_icons_by_extension() {
    
    
    
    HashMapElement icons[] = {
        {"1", L'\uf02d'},               // ""
        {"2", L'\uf02d'},               // ""
        {"3", L'\uf02d'},               // ""
        {"4", L'\uf02d'},               // ""
        {"5", L'\uf02d'},               // ""
        {"6", L'\uf02d'},               // ""
        {"7", L'\uf02d'},               // ""
        {"7z", L'\uf410'},              // ""
        {"8", L'\uf02d'},               // ""
        {"890", L'\U000f015e'},            // "󰅞"
        {"a", L'\ue624'},               // ""
        {"ai", L'\ue7b4'},              // ""
        {"ape", L'\uf001'},             // ""
        {"apk", L'\ue70e'},             // ""
        {"apng", L'\uf1c5'},            // ""
        {"ar", L'\uf410'},              // ""
        {"asc", L'\U000f099d'},            // "󰦝"
        {"asm", L'\uf471'},             // ""
        {"asp", L'\uf121'},             // ""
        {"avi", L'\uf008'},             // ""
        {"avif", L'\uf1c5'},            // ""
        {"avro", L'\ue60b'},            // ""
        {"awk", L'\uf489'},             // ""
        {"bak", L'\U000f006f'},            // "󰁯"
        {"bash_history", L'\U0000f489'},    // ""
        {"bash_profile", L'\U0000f489'},    // ""
        {"bashrc", L'\uf489'},          // ""
        {"bash", L'\uf489'},            // ""
        {"bat", L'\uf17a'},             // ""
        {"bin", L'\ueae8'},             // ""
        {"bio", L'\U000f0411'},            // "󰐑"
        {"blend", L'\U000f00ab'},          // "󰂫"
        {"blend1", L'\U000f00ab'},         // "󰂫"
        {"bmp", L'\uf1c5'},             // ""
        {"bz2", L'\uf410'},             // ""
        {"cc", L'\ue61d'},              // ""
        {"cfg", L'\ue615'},             // ""
        {"cip", L'\U000f015e'},            // "󰅞"
        {"cjs", L'\ue74e'},             // ""
        {"class", L'\ue738'},           // ""
        {"cljs", L'\ue76a'},            // ""
        {"clj", L'\ue768'},             // ""
        {"cls", L'\ue600'},             // ""
        {"cl", L'\U000f0172'},             // "󰅲"
        {"coffee", L'\uf0f4'},          // ""
        {"conf", L'\ue615'},            // ""
        {"cpp", L'\ue61d'},             // ""
        {"cp", L'\ue61d'},              // ""
        {"cshtml", L'\uf1fa'},          // ""
        {"csh", L'\uf489'},             // ""
        {"csproj", L'\U000f031b'},         // "󰌛"
        {"css", L'\ue749'},             // ""
        {"cs", L'\U000f031b'},             // "󰌛"
        {"csv", L'\uf1c3'},             // ""
        {"csx", L'\U000f031b'},            // "󰌛"
        {"cts", L'\ue628'},             // ""
        {"c++", L'\ue61d'},             // ""
        {"c", L'\ue61e'},               // ""
        {"cue", L'\uf001'},             // ""
        {"cxx", L'\ue61d'},             // ""
        {"cypher", L'\uf1c0'},          // ""
        {"dart", L'\ue798'},            // ""
        {"dat", L'\uf1c0'},             // ""
        {"db", L'\uf1c0'},              // ""
        {"deb", L'\uf187'},             // ""
        {"desktop", L'\uf108'},         // ""
        {"diff", L'\ue728'},            // ""
        {"dll", L'\uf17a'},             // ""
        {"dockerfile", L'\uf308'},      // ""
        {"doc", L'\uf1c2'},             // ""
        {"docx", L'\uf1c2'},            // ""
        {"download", L'\uf43a'},        // ""
        {"ds_store", L'\uf179'},        // ""
        {"dump", L'\uf1c0'},            // ""
        {"ebook", L'\ue28b'},           // ""
        {"ebuild", L'\uf30d'},          // ""
        {"eclass", L'\uf30d'},          // ""
        {"editorconfig", L'\ue615'},    // ""
        {"egg-info", L'\ue606'},        // ""
        {"ejs", L'\ue618'},             // ""
        {"elc", L'\U000f0172'},            // "󰅲"
        {"elf", L'\uf489'},             // ""
        {"elm", L'\ue62c'},             // ""
        {"el", L'\U000f0172'},             // "󰅲"
        {"env", L'\uf462'},             // ""
        {"eot", L'\uf031'},             // ""
        {"epub", L'\ue28a'},            // ""
        {"erb", L'\ue73b'},             // ""
        {"erl", L'\ue7b1'},             // ""
        {"exe", L'\uf17a'},             // ""
        {"exs", L'\ue62d'},             // ""
        {"ex", L'\ue62d'},              // ""
        {"fish", L'\uf489'},            // ""
        {"flac", L'\uf001'},            // ""
        {"flv", L'\uf008'},             // ""
        {"fnl", L'\ue6af'},             // ""
        {"font", L'\uf031'},            // ""
        {"fpl", L'\U000f0411'},            // "󰐑"
        {"fsi", L'\ue7a7'},             // ""
        {"fs", L'\ue7a7'},              // ""
        {"fsx", L'\ue7a7'},             // ""
        {"gdoc", L'\uf1c2'},            // ""
        {"gemfile", L'\ue21e'},         // ""
        {"gemspec", L'\ue21e'},         // ""
        {"gform", L'\uf298'},           // ""
        {"gif", L'\uf1c5'},             // ""
        {"git", L'\uf1d3'},             // ""
        {"go", L'\ue627'},              // ""
        {"gradle", L'\ue660'},          // ""
        {"gsheet", L'\uf1c3'},          // ""
        {"gslides", L'\uf1c4'},         // ""
        {"guardfile", L'\ue21e'},       // ""
        {"gv", L'\U000f1049'},             // "󱁉"
        {"gz", L'\uf410'},              // ""
        {"hbs", L'\ue60f'},             // ""
        {"heic", L'\uf1c5'},            // ""
        {"heif", L'\uf1c5'},            // ""
        {"heix", L'\uf1c5'},            // ""
        {"hh", L'\uf0fd'},              // ""
        {"hpp", L'\uf0fd'},             // ""
        {"hs", L'\ue777'},              // ""
        {"html", L'\uf13b'},            // ""
        {"htm", L'\uf13b'},             // ""
        {"h", L'\uf0fd'},               // ""
        {"hxx", L'\uf0fd'},             // ""
        {"ico", L'\uf1c5'},             // ""
        {"image", L'\uf1c5'},           // ""
        {"img", L'\uf1c0'},             // ""
        {"iml", L'\ue7b5'},             // ""
        {"info", L'\ue795'},            // ""
        {"in", L'\uf15c'},              // ""
        {"ini", L'\ue615'},             // ""
        {"ipynb", L'\ue606'},           // ""
        {"iso", L'\uf1c0'},             // ""
        {"j2", L'\ue000'},              // ""
        {"jar", L'\ue738'},             // ""
        {"java", L'\ue738'},            // ""
        {"jinja", L'\ue000'},           // ""
        {"jl", L'\ue624'},              // ""
        {"jpeg", L'\uf1c5'},            // ""
        {"jpg", L'\uf1c5'},             // ""
        {"jsonc", L'\ue60b'},           // ""
        {"json", L'\ue60b'},            // ""
        {"js", L'\ue74e'},              // ""
        {"jsx", L'\ue7ba'},             // ""
        {"key", L'\U000f0306'},            // "󰌆"
        {"ksh", L'\uf489'},             // ""
        {"kt", L'\ue634'},              // ""
        {"kts", L'\ue634'},             // ""
        {"kusto", L'\uf1c0'},           // ""
        {"ldb", L'\uf1c0'},             // ""
        {"ld", L'\ue624'},              // ""
        {"less", L'\ue758'},            // ""
        {"lhs", L'\ue777'},             // ""
        {"license", L'\ue60a'},         // ""
        {"lisp", L'\U000f0172'},           // "󰅲"
        {"list", L'\uf03a'},            // ""
        {"localized", L'\uf179'},       // ""
        {"lock", L'\uf023'},            // ""
        {"log", L'\uf18d'},             // ""
        {"lss", L'\ue749'},             // ""
        {"lua", L'\ue620'},             // ""
        {"lz", L'\uf410'},              // ""
        {"mgc", L'\uf0d0'},             // ""
        {"m3u8", L'\U000f0411'},           // "󰐑"
        {"m3u", L'\U000f0411'},            // "󰐑"
        {"m4a", L'\uf001'},             // ""
        {"m4v", L'\uf008'},             // ""
        {"magnet", L'\uf076'},          // ""
        {"malloy", L'\uf1c0'},          // ""
        {"man", L'\uf02d'},             // ""
        {"markdown", L'\ue609'},        // ""
        {"md", L'\ue609'},              // ""
        {"mjs", L'\ue74e'},             // ""
        {"mkd", L'\ue609'},             // ""
        {"mk", L'\uf085'},              // ""
        {"mkv", L'\uf008'},             // ""
        {"ml", L'\ue67a'},              // ""
        {"mli", L'\ue67a'},             // ""
        {"mll", L'\ue67a'},             // ""
        {"mly", L'\ue67a'},             // ""
        {"mobi", L'\ue28b'},            // ""
        {"mov", L'\uf008'},             // ""
        {"mp3", L'\uf001'},             // ""
        {"mp4", L'\uf008'},             // ""
        {"msi", L'\uf17a'},             // ""
        {"mts", L'\ue628'},             // ""
        {"mustache", L'\ue60f'},        // ""
        {"nim", L'\ue677'},             // ""
        {"nimble", L'\ue677'},          // ""
        {"nix", L'\uf313'},             // ""
        {"npmignore", L'\ue71e'},       // ""
        {"odp", L'\uf1c4'},             // ""
        {"ods", L'\uf1c3'},             // ""
        {"odt", L'\uf1c2'},             // ""
        {"ogg", L'\uf001'},             // ""
        {"ogv", L'\uf008'},             // ""
        {"old", L'\U000f006f'},            // "󰁯"
        {"opus", L'\uf001'},            // ""
        {"orig", L'\U000f006f'},           // "󰁯"
        {"org", L'\ue633'},             // ""
        {"otf", L'\uf031'},             // ""
        {"o", L'\ueae8'},               // ""
        {"part", L'\uf43a'},            // ""
        {"patch", L'\ue728'},           // ""
        {"pdb", L'\U000f0aaa'},            // "󰪪"
        {"pdf", L'\uf1c1'},             // ""
        {"pem", L'\U000f0306'},            // "󰌆"
        {"phar", L'\ue608'},            // ""
        {"php", L'\ue608'},             // ""
        {"pkg", L'\uf187'},             // ""
        {"pl", L'\ue67e'},              // ""
        {"plist", L'\uf302'},           // ""
        {"pls", L'\U000f0411'},            // "󰐑"
        {"plx", L'\ue67e'},             // ""
        {"pm", L'\ue67e'},              // ""
        {"png", L'\uf1c5'},             // ""
        {"pod", L'\ue67e'},             // ""
        {"pp", L'\ue631'},              // ""
        {"ppt", L'\uf1c4'},             // ""
        {"pptx", L'\uf1c4'},            // ""
        {"procfile", L'\ue21e'},        // ""
        {"properties", L'\ue60b'},      // ""
        {"prql", L'\uf1c0'},            // ""
        {"ps1", L'\uf489'},             // ""
        {"psd", L'\ue7b8'},             // ""
        {"pub", L'\U000f0306'},            // "󰌆"
        {"sbv", L'\U000f015e'},            // "󰅞"
        {"scc", L'\U000f015e'},            // "󰅞"
        {"slt", L'\U000f0221'},            // "󰈡"
        {"smi", L'\U000f015e'},            // "󰅞"
        {"pxm", L'\uf1c5'},             // ""
        {"pyc", L'\ue606'},             // ""
        {"py", L'\ue606'},              // ""
        {"rakefile", L'\ue21e'},        // ""
        {"rar", L'\uf410'},             // ""
        {"razor", L'\uf1fa'},           // ""
        {"rb", L'\ue21e'},              // ""
        {"rdata", L'\U000f07d4'},          // "󰟔"
        {"rdb", L'\ue76d'},             // ""
        {"rdoc", L'\ue609'},            // ""
        {"rds", L'\U000f07d4'},            // "󰟔"
        {"readme", L'\ue609'},          // ""
        {"rlib", L'\ue68b'},            // ""
        {"rl", L'\uf11c'},              // ""
        {"rmd", L'\ue609'},             // ""
        {"rmeta", L'\ue68b'},           // ""
        {"rpm", L'\uf187'},             // ""
        {"rproj", L'\U000f05c6'},          // "󰗆"
        {"rq", L'\uf1c0'},              // ""
        {"rspec_parallel", L'\ue21e'},  // ""
        {"rspec_status", L'\ue21e'},    // ""
        {"rspec", L'\ue21e'},           // ""
        {"rss", L'\uf09e'},             // ""
        {"rs", L'\ue68b'},              // ""
        {"rtf", L'\uf15c'},             // ""
        {"rubydoc", L'\ue73b'},         // ""
        {"r", L'\U000f07d4'},              // "󰟔"
        {"ru", L'\ue21e'},              // ""
        {"sass", L'\ue603'},            // ""
        {"scala", L'\ue737'},           // ""
        {"scpt", L'\uf302'},            // ""
        {"scss", L'\ue603'},            // ""
        {"shell", L'\uf489'},           // ""
        {"sh", L'\uf489'},              // ""
        {"sig", L'\ue60a'},             // ""
        {"slim", L'\ue73b'},            // ""
        {"sln", L'\ue70c'},             // ""
        {"so", L'\ue624'},              // ""
        {"sqlite3", L'\ue7c4'},         // ""
        {"sql", L'\uf1c0'},             // ""
        {"srt", L'\U000f0a16'},            // "󰨖"
        {"styl", L'\ue600'},            // ""
        {"stylus", L'\ue600'},          // ""
        {"sublime-menu", L'\ue7aa'},    // ""
        {"sublime-package", L'\ue7aa'}, // ""
        {"sublime-project", L'\ue7aa'}, // ""
        {"sublime-session", L'\ue7aa'}, // ""
        {"sub", L'\U000f0a16'},            // "󰨖"
        {"s", L'\uf471'},               // ""
        {"svg", L'\uf1c5'},             // ""
        {"svelte", L'\ue697'},          // ""
        {"swift", L'\ue755'},           // ""
        {"swp", L'\ue62b'},             // ""
        {"sym", L'\ueae8'},             // ""
        {"tar", L'\uf410'},             // ""
        {"taz", L'\uf410'},             // ""
        {"tbz", L'\uf410'},             // ""
        {"tbz2", L'\uf410'},            // ""
        {"tex", L'\ue600'},             // ""
        {"tgz", L'\uf410'},             // ""
        {"tiff", L'\uf1c5'},            // ""
        {"timestamp", L'\uf43a'},       // ""
        {"toml", L'\ue60b'},            // ""
        {"torrent", L'\U000f048d'},        // "󰒍"
        {"trash", L'\uf1f8'},           // ""
        {"ts", L'\ue628'},              // ""
        {"tsx", L'\ue7ba'},             // ""
        {"ttc", L'\uf031'},             // ""
        {"ttf", L'\uf031'},             // ""
        {"t", L'\ue769'},               // ""
        {"twig", L'\ue61c'},            // ""
        {"txt", L'\uf15c'},             // ""
        {"unity", L'\ue721'},           // ""
        {"unity32", L'\ue721'},         // ""
        {"video", L'\uf008'},           // ""
        {"vim", L'\ue62b'},             // ""
        {"vlc", L'\U000f0411'},            // "󰐑"
        {"vtt", L'\U000f015e'},            // "󰅞"
        {"vue", L'\U000f0844'},            // "󰡄"
        {"wav", L'\uf001'},             // ""
        {"webm", L'\uf008'},            // ""
        {"webp", L'\uf1c5'},            // ""
        {"whl", L'\uf487'},             // ""
        {"windows", L'\uf17a'},         // ""
        {"wma", L'\uf001'},             // ""
        {"wmv", L'\uf008'},             // ""
        {"woff2", L'\uf031'},           // ""
        {"woff", L'\uf031'},            // ""
        {"wpl", L'\U000f0411'},            // "󰐑"
        {"xbps", L'\uf187'},            // ""
        {"xcf", L'\uf1c5'},             // ""
        {"xls", L'\uf1c3'},             // ""
        {"xlsx", L'\uf1c3'},            // ""
        {"xml", L'\uf121'},             // ""
        {"xul", L'\uf269'},             // ""
        {"xz", L'\uf410'},              // ""
        {"yaml", L'\ue60b'},            // ""
        {"yml", L'\ue60b'},             // ""
        {"zip", L'\uf410'},             // ""
        {"zig", L'\ue6a9'},             // ""
        {"zon", L'\ue60b'},             // ""
        {"zshrc", L'\uf489'},           // ""
        {"zsh-theme", L'\uf489'},       // ""
        {"zsh", L'\uf489'},             // ""
        {"zst", L'\uf410'},             // ""
        {NULL, NULL}
    };

    return icons;
}



// dir: "\u{f115}".into(),           // 
// file: "\u{f016}".into(),          // 
// pipe: "\u{f0232}".into(),         // 󰈲
// socket: "\u{f01a8}".into(),       // 󰆨
// executable: "\u{f489}".into(),    // 
// symlink_dir: "\u{f482}".into(),   // 
// symlink_file: "\u{f481}".into(),  // 
// device_char: "\u{e601}".into(),   // 
// device_block: "\u{f072b}".into(), // 󰜫
// special: "\u{f2dc}".into(),       // 





HashMapElement* get_default_icons_by_name() {
    HashMapElement icons[] = {
        {"a.out",                  L'\uf489'},            // ""
        {"api",                    L'\U000f048d'},        // "󰒍"
        {".asoundrc",              L'\ue615'},            // ""
        {".atom",                  L'\ue764'},            // ""
        {".ash",                   L'\uf489'},            // ""
        {".ash_history",           L'\uf489'},            // ""
        {"authorized_keys",        L'\ue60a'},            // ""
        {"assets",                 L'\uf0c7'},            // ""
        {".android",               L'\uf17b'},            // ""
        {".audacity-data",         L'\ue5fc'},            // ""
        {"backups",                L'\U000f006f'},        // "󰁯"
        {".bash_history",          L'\U000f1183'},        // "󱆃"
        {".bash_logout",           L'\U000f1183'},        // "󱆃"
        {".bash_profile",          L'\U000f1183'},        // "󱆃"
        {".bashrc",                L'\U000f1183'},        // "󱆃"
        {"bin",                    L'\ue5fc'},            // ""
        {".bpython_history",       L'\ue606'},            // ""
        {"build",                  L'\uf487'},            // ""
        {"bspwmrc",                L'\ue615'},            // ""
        {"build.ninja",            L'\uf0ad'},            // ""
        {".cache",                 L'\U000f00e8'},        // "󰃨"
        {"cache",                  L'\U000f00e8'},        // "󰃨"
        {"cargo.lock",             L'\ue68b'},            // ""
        {"cargo.toml",             L'\ue68b'},            // ""
        {".cargo",                 L'\ue68b'},            // ""
        {".ccls-cache",            L'\U000f00e8'},        // "󰃨"
        {"changelog",              L'\ue609'},            // ""
        {".clang-format",          L'\ue615'},            // ""
        {"composer.json",          L'\ue608'},            // ""
        {"composer.lock",          L'\ue608'},            // ""
        {"conf.d",                 L'\ue5fc'},            // ""
        {"config.ac",              L'\ue615'},            // ""
        {"config.el",              L'\ue632'},            // ""
        {"config.mk",              L'\ue615'},            // ""
        {".config",                L'\ue5fc'},            // ""
        {"config",                 L'\ue5fc'},            // ""
        {"configure",              L'\uf0ad'},            // ""
        {"content",                L'\uf0c7'},            // ""
        {"contributing",           L'\ue60a'},            // ""
        {"copyright",              L'\ue60a'},            // ""
        {"cron.daily",             L'\ue5fc'},            // ""
        {"cron.d",                 L'\ue5fc'},            // ""
        {"cron.deny",              L'\ue615'},            // ""
        {"cron.hourly",            L'\ue5fc'},            // ""
        {"cron.monthly",           L'\ue5fc'},            // ""
        {"crontab",                L'\ue615'},            // ""
        {"cron.weekly",            L'\ue5fc'},            // ""
        {"crypttab",               L'\ue615'},            // ""
        {".cshrc",                 L'\U000f1183'},        // "󱆃"
        {"csh.cshrc",              L'\U000f1183'},        // "󱆃"
        {"csh.login",              L'\U000f1183'},        // "󱆃"
        {"csh.logout",             L'\U000f1183'},        // "󱆃"
        {"css",                    L'\ue749'},            // ""
        {"custom.el",              L'\ue632'},            // ""
        {".dbus",                  L'\uf013'},            // ""
        {"desktop",                L'\uf108'},            // ""
        {"docker-compose.yml",     L'\uf308'},            // ""
        {"dockerfile",             L'\uf308'},            // ""
        {"doc",                    L'\uf02d'},            // ""
        {"dist",                   L'\uf487'},            // ""
        {"documents",              L'\uf02d'},            // ""
        {".doom.d",                L'\ue632'},            // ""
        {"downloads",              L'\U000f024d'},        // "󰉍"
        {".ds_store",              L'\uf179'},            // ""
        {".editorconfig",          L'\ue615'},            // ""
        {".electron-gyp",          L'\ue5fa'},            // ""
        {".emacs.d",               L'\ue632'},            // ""
        {".env",                   L'\uf462'},            // ""
        {"environment",            L'\uf462'},            // ""
        {".eslintrc.json",         L'\uf462'},            // ""
        {".eslintrc.js",           L'\uf462'},            // ""
        {".eslintrc.yml",          L'\uf462'},            // ""
        {"etc",                    L'\ue5fc'},            // ""
        {"favicon.ico",            L'\uf005'},            // ""
        {"favicons",               L'\uf005'},            // ""
        {".fennelrc",              L'\ue615'},            // ""
        {"fstab",                  L'\uf1c0'},            // ""
        {".fastboot",              L'\uf17b'},            // ""
        {".gitattributes",         L'\uf1d3'},            // ""
        {".gitconfig",             L'\uf1d3'},            // ""
        {".git-credentials",       L'\ue60a'},            // ""
        {".github",                L'\ue5fd'},            // ""
        {"gitignore_global",       L'\uf1d3'},            // ""
        {".gitignore",             L'\uf1d3'},            // ""
        {".gitlab-ci.yml",         L'\uf296'},            // ""
        {".gitmodules",            L'\uf1d3'},            // ""
        {".git",                   L'\ue5fb'},            // ""
        {".gnupg",                 L'\U000f08ac'},        // "󰢬"
        {"go.mod",                 L'\ue627'},            // ""
        {"go.sum",                 L'\ue627'},            // ""
        {"go.work",                L'\ue627'},            // ""
        {"gradle",                 L'\ue660'},            // ""
        {"gradle.properties",      L'\ue660'},            // ""
        {"gradlew",                L'\ue660'},            // ""
        {"gradlew.bat",            L'\ue660'},            // ""
        {"group",                  L'\ue615'},            // ""
        {"gruntfile.coffee",       L'\ue611'},            // ""
        {"gruntfile.js",           L'\ue611'},            // ""
        {"gruntfile.ls",           L'\ue611'},            // ""
        {"gshadow",                L'\ue615'},            // ""
        {"gulpfile.coffee",        L'\ue610'},            // ""
        {"gulpfile.js",            L'\ue610'},            // ""
        {"gulpfile.ls",            L'\ue610'},            // ""
        {"heroku.yml",             L'\ue77b'},            // ""
        {"hidden",                 L'\uf023'},            // ""
        {"home",                   L'\uf015'},            // ""
        {"hostname",               L'\ue615'},            // ""
        {"hosts",                  L'\U000f0002'},        // "󰀂"
        {".htaccess",              L'\ue615'},            // ""
        {"htoprc",                 L'\ue615'},            // ""
        {".htpasswd",              L'\ue615'},            // ""
        {".icons",                 L'\uf005'},            // ""
        {"icons",                  L'\uf005'},            // ""
        {"id_dsa",                 L'\U000f0dd6'},        // "󰷖"
        {"id_ecdsa",               L'\U000f0dd6'},        // "󰷖"
        {"id_rsa",                 L'\U000f0dd6'},        // "󰷖"
        {".idlerc",                L'\ue235'},            // ""
        {"img",                    L'\uf1c5'},            // ""
        {"include",                L'\ue5fc'},            // ""
        {"init.el",                L'\ue632'},            // ""
        {".inputrc",               L'\ue615'},            // ""
        {"inputrc",                L'\ue615'},            // ""
        {".java",                  L'\ue256'},            // ""
        {"jenkinsfile",            L'\ue66e'},            // ""
        {"js",                     L'\ue74e'},            // ""
        {".jupyter",               L'\ue606'},            // ""
        {"kbuild",                 L'\ue615'},            // ""
        {"kconfig",                L'\ue615'},            // ""
        {"kdeglobals",             L'\ue615'},            // ""
        {"kdenliverc",             L'\ue615'},            // ""
        {"known_hosts",            L'\ue60a'},            // ""
        {".kshrc",                 L'\uf489'},            // ""
        {"libexec",                L'\uf121'},            // ""
        {"lib32",                  L'\uf121'},            // ""
        {"lib64",                  L'\uf121'},            // ""
        {"lib",                    L'\uf121'},            // ""
        {"license.md",             L'\ue60a'},            // ""
        {"licenses",               L'\ue60a'},            // ""
        {"license.txt",            L'\ue60a'},            // ""
        {"license",                L'\ue60a'},            // ""
        {"localized",              L'\uf179'},            // ""
        {"lsb-release",            L'\ue615'},            // ""
        {".lynxrc",                L'\ue615'},            // ""
        {".mailcap",               L'\U000f01f0'},        // "󰇰"
        {"mail",                   L'\U000f01f0'},        // "󰇰"
        {"magic",                  L'\uf0d0'},            // ""
        {"maintainers",            L'\ue60a'},            // ""
        {"makefile.ac",            L'\ue615'},            // ""
        {"makefile",               L'\ue615'},            // ""
        {"manifest",               L'\uf292'},            // ""
        {"md5sum",                 L'\U000f0565'},        // "󰕥"
        {"meson.build",            L'\uf0ad'},            // ""
        {"metadata",               L'\ue5fc'},            // ""
        {"metadata.xml",           L'\uf462'},            // ""
        {"media",                  L'\uf40f'},            // ""
        {".mime.types",            L'\U000f0645'},        // "󰙅"
        {"mime.types",             L'\U000f0645'},        // "󰙅"
        {"module.symvers",         L'\uf471'},            // ""
        {".mozilla",               L'\ue786'},            // ""
        {"music",                  L'\U000f1359'},        // "󱍙"
        {"muttrc",                 L'\ue615'},            // ""
        {".muttrc",                L'\ue615'},            // ""
        {".mutt",                  L'\ue615'},            // ""
        {".mypy_cache",            L'\U000f00e8'},        // "󰃨"
        {"neomuttrc",              L'\ue615'},            // ""
        {".neomuttrc",             L'\ue615'},            // ""
        {"netlify.toml",           L'\uf233'},            // ""
        {".nix-channels",          L'\uf313'},            // ""
        {".nix-defexpr",           L'\uf313'},            // ""
        {".node-gyp",              L'\ue5fa'},            // ""
        {"node_modules",           L'\ue5fa'},            // ""
        {".node_repl_history",     L'\ue718'},            // ""
        {"npmignore",              L'\ue71e'},            // ""
        {".npm",                   L'\ue5fa'},            // ""
        {"nvim",                   L'\uf36f'},            // ""
        {"obj",                    L'\ue624'},            // ""
        {"os-release",             L'\ue615'},            // ""
        {"package.json",           L'\ue718'},            // ""
        {"package-lock.json",      L'\ue718'},            // ""
        {"packages.el",            L'\ue632'},            // ""
        {"pam.d",                  L'\U000f08ac'},        // "󰢬"
        {"passwd",                 L'\uf023'},            // ""
        {"pictures",               L'\U000f024f'},        // "󰉏"
        {"pkgbuild",               L'\uf303'},            // ""
        {".pki",                   L'\uf023'},            // ""
        {"portage",                L'\uf30d'},            // ""
        {"profile",                L'\ue615'},            // ""
        {".profile",               L'\ue615'},            // ""
        {"public",                 L'\uf415'},            // ""
        {"__pycache__",            L'\ue606'},            // ""
        {"pyproject.toml",         L'\ue606'},            // ""
        {".python_history",        L'\ue606'},            // ""
        {".pypirc",                L'\ue606'},            // ""
        {"rc.lua",                 L'\ue615'},            // ""
        {"readme",                 L'\ue609'},            // ""
        {".release.toml",          L'\ue68b'},            // ""
        {"requirements.txt",       L'\U000f0320'},        // "󰌠"
        {"robots.txt",             L'\U000f06a9'},        // "󰚩"
        {"root",                   L'\U000f0250'},        // "󰉐"
        {"rubydoc",                L'\ue73b'},            // ""
        {"runtime.txt",            L'\U000f0320'},        // "󰌠"
        {".rustup",                L'\ue68b'},            // ""
        {"rustfmt.toml",           L'\ue68b'},            // ""
        {".rvm",                   L'\ue21e'},            // ""
        {"sass",                   L'\ue603'},            // ""
        {"sbin",                   L'\ue5fc'},            // ""
        {"scripts",                L'\uf489'},            // ""
        {"scss",                   L'\ue603'},            // ""
        {"sha256sum",              L'\U000f0565'},        // "󰕥"
        {"shadow",                 L'\ue615'},            // ""
        {"share",                  L'\uf064'},            // ""
        {".shellcheckrc",          L'\ue615'},            // ""
        {"shells",                 L'\ue615'},            // ""
        {".spacemacs",             L'\ue632'},            // ""
        {".sqlite_history",        L'\ue7c4'},            // ""
        {"src",                    L'\U000f19fc'},        // "󱧼"
        {".ssh",                   L'\U000f08ac'},        // "󰢬"
        {"static",                 L'\uf0c7'},            // ""
        {"std",                    L'\U000f0171'},        // "󰅱"
        {"styles",                 L'\ue749'},            // ""
        {"subgid",                 L'\ue615'},            // ""
        {"subuid",                 L'\ue615'},            // ""
        {"sudoers",                L'\uf023'},            // ""
        {"sxhkdrc",                L'\ue615'},            // ""
        {"template",               L'\uf32e'},            // ""
        {"tests",                  L'\U000f0668'},        // "󰙨"
        {"tigrc",                  L'\ue615'},            // ""
        {"timezone",               L'\uf43a'},            // ""
        {"tox.ini",                L'\ue615'},            // ""
        {".trash",                 L'\uf1f8'},            // ""
        {"ts",                     L'\ue628'},            // ""
        {".tox",                   L'\ue606'},            // ""
        {"unlicense",              L'\ue60a'},            // ""
        {"url",                    L'\uf0ac'},            // ""
        {"user-dirs.dirs",         L'\ue5fc'},            // ""
        {"vagrantfile",            L'\ue615'},            // ""
        {"vendor",                 L'\U000f0ae6'},        // "󰫦"
        {"venv",                   L'\U000f0320'},        // "󰌠"
        {"videos",                 L'\uf03d'},            // ""
        {".viminfo",               L'\ue62b'},            // ""
        {".vimrc",                 L'\ue62b'},            // ""
        {"vimrc",                  L'\ue62b'},            // ""
        {".vim",                   L'\ue62b'},            // ""
        {"vim",                    L'\ue62b'},            // ""
        {".vscode",                L'\ue70c'},            // ""
        {"webpack.config.js",      L'\U000f072b'},        // "󰜫"
        {".wgetrc",                L'\ue615'},            // ""
        {"wgetrc",                 L'\ue615'},            // ""
        {".xauthority",            L'\ue615'},            // ""
        {".Xauthority",            L'\ue615'},            // ""
        {"xbps.d",                 L'\uf32e'},            // ""
        {"xbps-src",               L'\uf32e'},            // ""
        {".xinitrc",               L'\ue615'},            // ""
        {".xmodmap",               L'\ue615'},            // ""
        {".Xmodmap",               L'\ue615'},            // ""
        {"xmonad.hs",              L'\ue615'},            // ""
        {"xorg.conf.d",            L'\ue5fc'},            // ""
        {".xprofile",              L'\ue615'},            // ""
        {".Xprofile",              L'\ue615'},            // ""
        {".xresources",            L'\ue615'},            // ""
        {".yarnrc",                L'\ue6a7'},            // ""
        {"yarn.lock",              L'\ue6a7'},            // ""
        {"zathurarc",              L'\ue615'},            // ""
        {".zcompdump",             L'\ue615'},            // ""
        {".zlogin",                L'\U000f1183'},        // "󱆃"
        {".zlogout",               L'\U000f1183'},        // "󱆃"
        {".zprofile",              L'\U000f1183'},        // "󱆃"
        {".zsh_history",           L'\U000f1183'},        // "󱆃"
        {".zshrc",                 L'\U000f1183'},        // "󱆃"
        {NULL,                     NULL}
    };

    return icons;
}
*/
