#include "../include/icon_parse.h"
#include "../include/shared.h"
#include "../include/uthash.h"
#include <ncurses.h>
#include <wchar.h>
#include <string.h>


void free_icon_map(HashMapElement* map) {
    HashMapElement *current, *tmp;
    HASH_ITER(hh, map, current, tmp) {
        HASH_DEL(map, current);   // Rimuovi elemento
        free(current->key);        // Libera memoria della stringa
        free(current);                   // Libera la struttura
    }
}

void init_all() {
  init_icon_by_extension_map();
  init_icon_by_name_map();
}

void free_all(){
  free_icon_map(icons_by_extension);
  free_icon_map(icons_by_name);
}



/**
* Main function of this file.
* Given a node this returns the associated icon
* 
* Example of intended usage:
* 
* init_all();
* get_icon_from_path(node); // here u can use this 
* free_all();
* 
* and YES, it is FANCY 
*/
wchar_t get_icon_for_path(Node *node) {
    char *extension;
    char *filename;
    wchar_t icon;

    switch (node->type) {
      case T_DIR:
        filename = getFileName(node->name);
        icon = get_icon(icons_by_name, filename);
        if (icon == ' ')
          return DEFAULT_DIR_ICON; 
        break;
      case T_FILE:
        extension = strrchr(getFileName(node->name), '.');
        icon = get_icon(icons_by_extension, extension);
        if (icon == ' ') 
          return DEFAULT_FILE_ICON;
        break;  
      case T_EXE:
        icon = DEFAULT_EXE_ICON;
        break;
      case T_DIR_LINK:
        icon = DIR_LINK_ICON;
        break;
      case T_FILE_LINK:
        icon = FILE_LINK_ICON;
        break;
      default:
        icon = DEFAULT_FILE_ICON;
        break;
    }

    return icon;
   
}


void add_icon(HashMapElement map[], char *key, wchar_t icon) {
    HashMapElement *entry = malloc(sizeof(HashMapElement));
    entry->key = strdup(key);  // Copia l'estensione
    entry->icon = icon;              // Assegna l'icona
    HASH_ADD_KEYPTR(hh, map, entry->key, strlen(entry->key), entry);
}


wchar_t get_icon(HashMapElement map[], char *key) {
    HashMapElement *entry;
    HASH_FIND_STR(map, key, entry);  // Cerca nella tabella
    return entry ? entry->icon : ' ';           // Ritorna l'icona o un'icona predefinita
}







void init_icon_by_extension_map() {
        add_icon(icons_by_extension, "1", L'\uf02d');               // ""
        add_icon(icons_by_extension, "2", L'\uf02d');               // ""
        add_icon(icons_by_extension, "3", L'\uf02d');               // ""
        add_icon(icons_by_extension, "4", L'\uf02d');               // ""
        add_icon(icons_by_extension, "5", L'\uf02d');               // ""
        add_icon(icons_by_extension, "6", L'\uf02d');               // ""
        add_icon(icons_by_extension, "7", L'\uf02d');               // ""
        add_icon(icons_by_extension, "7z", L'\uf410');              // ""
        add_icon(icons_by_extension, "8", L'\uf02d');               // ""
        add_icon(icons_by_extension, "890", L'\U000f015e');            // "󰅞"
        add_icon(icons_by_extension, "a", L'\ue624');               // ""
        add_icon(icons_by_extension, "ai", L'\ue7b4');              // ""
        add_icon(icons_by_extension, "ape", L'\uf001');             // ""
        add_icon(icons_by_extension, "apk", L'\ue70e');             // ""
        add_icon(icons_by_extension, "apng", L'\uf1c5');            // ""
        add_icon(icons_by_extension, "ar", L'\uf410');              // ""
        add_icon(icons_by_extension, "asc", L'\U000f099d');            // "󰦝"
        add_icon(icons_by_extension, "asm", L'\uf471');             // ""
        add_icon(icons_by_extension, "asp", L'\uf121');             // ""
        add_icon(icons_by_extension, "avi", L'\uf008');             // ""
        add_icon(icons_by_extension, "avif", L'\uf1c5');            // ""
        add_icon(icons_by_extension, "avro", L'\ue60b');            // ""
        add_icon(icons_by_extension, "awk", L'\uf489');             // ""
        add_icon(icons_by_extension, "bak", L'\U000f006f');            // "󰁯"
        add_icon(icons_by_extension, "bash_history", L'\U0000f489');    // ""
        add_icon(icons_by_extension, "bash_profile", L'\U0000f489');    // ""
        add_icon(icons_by_extension, "bashrc", L'\uf489');          // ""
        add_icon(icons_by_extension, "bash", L'\uf489');            // ""
        add_icon(icons_by_extension, "bat", L'\uf17a');             // ""
        add_icon(icons_by_extension, "bin", L'\ueae8');             // ""
        add_icon(icons_by_extension, "bio", L'\U000f0411');            // "󰐑"
        add_icon(icons_by_extension, "blend", L'\U000f00ab');          // "󰂫"
        add_icon(icons_by_extension, "blend1", L'\U000f00ab');         // "󰂫"
        add_icon(icons_by_extension, "bmp", L'\uf1c5');             // ""
        add_icon(icons_by_extension, "bz2", L'\uf410');             // ""
        add_icon(icons_by_extension, "cc", L'\ue61d');              // ""
        add_icon(icons_by_extension, "cfg", L'\ue615');             // ""
        add_icon(icons_by_extension, "cip", L'\U000f015e');            // "󰅞"
        add_icon(icons_by_extension, "cjs", L'\ue74e');             // ""
        add_icon(icons_by_extension, "class", L'\ue738');           // ""
        add_icon(icons_by_extension, "cljs", L'\ue76a');            // ""
        add_icon(icons_by_extension, "clj", L'\ue768');             // ""
        add_icon(icons_by_extension, "cls", L'\ue600');             // ""
        add_icon(icons_by_extension, "cl", L'\U000f0172');             // "󰅲"
        add_icon(icons_by_extension, "coffee", L'\uf0f4');          // ""
        add_icon(icons_by_extension, "conf", L'\ue615');            // ""
        add_icon(icons_by_extension, "cpp", L'\ue61d');             // ""
        add_icon(icons_by_extension, "cp", L'\ue61d');              // ""
        add_icon(icons_by_extension, "cshtml", L'\uf1fa');          // ""
        add_icon(icons_by_extension, "csh", L'\uf489');             // ""
        add_icon(icons_by_extension, "csproj", L'\U000f031b');         // "󰌛"
        add_icon(icons_by_extension, "css", L'\ue749');             // ""
        add_icon(icons_by_extension, "cs", L'\U000f031b');             // "󰌛"
        add_icon(icons_by_extension, "csv", L'\uf1c3');             // ""
        add_icon(icons_by_extension, "csx", L'\U000f031b');            // "󰌛"
        add_icon(icons_by_extension, "cts", L'\ue628');             // ""
        add_icon(icons_by_extension, "c++", L'\ue61d');             // ""
        add_icon(icons_by_extension, "c", L'\ue61e');               // ""
        add_icon(icons_by_extension, "cue", L'\uf001');             // ""
        add_icon(icons_by_extension, "cxx", L'\ue61d');             // ""
        add_icon(icons_by_extension, "cypher", L'\uf1c0');          // ""
        add_icon(icons_by_extension, "dart", L'\ue798');            // ""
        add_icon(icons_by_extension, "dat", L'\uf1c0');             // ""
        add_icon(icons_by_extension, "db", L'\uf1c0');              // ""
        add_icon(icons_by_extension, "deb", L'\uf187');             // ""
        add_icon(icons_by_extension, "desktop", L'\uf108');         // ""
        add_icon(icons_by_extension, "diff", L'\ue728');            // ""
        add_icon(icons_by_extension, "dll", L'\uf17a');             // ""
        add_icon(icons_by_extension, "dockerfile", L'\uf308');      // ""
        add_icon(icons_by_extension, "doc", L'\uf1c2');             // ""
        add_icon(icons_by_extension, "docx", L'\uf1c2');            // ""
        add_icon(icons_by_extension, "download", L'\uf43a');        // ""
        add_icon(icons_by_extension, "ds_store", L'\uf179');        // ""
        add_icon(icons_by_extension, "dump", L'\uf1c0');            // ""
        add_icon(icons_by_extension, "ebook", L'\ue28b');           // ""
        add_icon(icons_by_extension, "ebuild", L'\uf30d');          // ""
        add_icon(icons_by_extension, "eclass", L'\uf30d');          // ""
        add_icon(icons_by_extension, "editorconfig", L'\ue615');    // ""
        add_icon(icons_by_extension, "egg-info", L'\ue606');        // ""
        add_icon(icons_by_extension, "ejs", L'\ue618');             // ""
        add_icon(icons_by_extension, "elc", L'\U000f0172');            // "󰅲"
        add_icon(icons_by_extension, "elf", L'\uf489');             // ""
        add_icon(icons_by_extension, "elm", L'\ue62c');             // ""
        add_icon(icons_by_extension, "el", L'\U000f0172');             // "󰅲"
        add_icon(icons_by_extension, "env", L'\uf462');             // ""
        add_icon(icons_by_extension, "eot", L'\uf031');             // ""
        add_icon(icons_by_extension, "epub", L'\ue28a');            // ""
        add_icon(icons_by_extension, "erb", L'\ue73b');             // ""
        add_icon(icons_by_extension, "erl", L'\ue7b1');             // ""
        add_icon(icons_by_extension, "exe", L'\uf17a');             // ""
        add_icon(icons_by_extension, "exs", L'\ue62d');             // ""
        add_icon(icons_by_extension, "ex", L'\ue62d');              // ""
        add_icon(icons_by_extension, "fish", L'\uf489');            // ""
        add_icon(icons_by_extension, "flac", L'\uf001');            // ""
        add_icon(icons_by_extension, "flv", L'\uf008');             // ""
        add_icon(icons_by_extension, "fnl", L'\ue6af');             // ""
        add_icon(icons_by_extension, "font", L'\uf031');            // ""
        add_icon(icons_by_extension, "fpl", L'\U000f0411');            // "󰐑"
        add_icon(icons_by_extension, "fsi", L'\ue7a7');             // ""
        add_icon(icons_by_extension, "fs", L'\ue7a7');              // ""
        add_icon(icons_by_extension, "fsx", L'\ue7a7');             // ""
        add_icon(icons_by_extension, "gdoc", L'\uf1c2');            // ""
        add_icon(icons_by_extension, "gemfile", L'\ue21e');         // ""
        add_icon(icons_by_extension, "gemspec", L'\ue21e');         // ""
        add_icon(icons_by_extension, "gform", L'\uf298');           // ""
        add_icon(icons_by_extension, "gif", L'\uf1c5');             // ""
        add_icon(icons_by_extension, "git", L'\uf1d3');             // ""
        add_icon(icons_by_extension, "go", L'\ue627');              // ""
        add_icon(icons_by_extension, "gradle", L'\ue660');          // ""
        add_icon(icons_by_extension, "gsheet", L'\uf1c3');          // ""
        add_icon(icons_by_extension, "gslides", L'\uf1c4');         // ""
        add_icon(icons_by_extension, "guardfile", L'\ue21e');       // ""
        add_icon(icons_by_extension, "gv", L'\U000f1049');             // "󱁉"
        add_icon(icons_by_extension, "gz", L'\uf410');              // ""
        add_icon(icons_by_extension, "hbs", L'\ue60f');             // ""
        add_icon(icons_by_extension, "heic", L'\uf1c5');            // ""
        add_icon(icons_by_extension, "heif", L'\uf1c5');            // ""
        add_icon(icons_by_extension, "heix", L'\uf1c5');            // ""
        add_icon(icons_by_extension, "hh", L'\uf0fd');              // ""
        add_icon(icons_by_extension, "hpp", L'\uf0fd');             // ""
        add_icon(icons_by_extension, "hs", L'\ue777');              // ""
        add_icon(icons_by_extension, "html", L'\uf13b');            // ""
        add_icon(icons_by_extension, "htm", L'\uf13b');             // ""
        add_icon(icons_by_extension, "h", L'\uf0fd');               // ""
        add_icon(icons_by_extension, "hxx", L'\uf0fd');             // ""
        add_icon(icons_by_extension, "ico", L'\uf1c5');             // ""
        add_icon(icons_by_extension, "image", L'\uf1c5');           // ""
        add_icon(icons_by_extension, "img", L'\uf1c0');             // ""
        add_icon(icons_by_extension, "iml", L'\ue7b5');             // ""
        add_icon(icons_by_extension, "info", L'\ue795');            // ""
        add_icon(icons_by_extension, "in", L'\uf15c');              // ""
        add_icon(icons_by_extension, "ini", L'\ue615');             // ""
        add_icon(icons_by_extension, "ipynb", L'\ue606');           // ""
        add_icon(icons_by_extension, "iso", L'\uf1c0');             // ""
        add_icon(icons_by_extension, "j2", L'\ue000');              // ""
        add_icon(icons_by_extension, "jar", L'\ue738');             // ""
        add_icon(icons_by_extension, "java", L'\ue738');            // ""
        add_icon(icons_by_extension, "jinja", L'\ue000');           // ""
        add_icon(icons_by_extension, "jl", L'\ue624');              // ""
        add_icon(icons_by_extension, "jpeg", L'\uf1c5');            // ""
        add_icon(icons_by_extension, "jpg", L'\uf1c5');             // ""
        add_icon(icons_by_extension, "jsonc", L'\ue60b');           // ""
        add_icon(icons_by_extension, "json", L'\ue60b');            // ""
        add_icon(icons_by_extension, "js", L'\ue74e');              // ""
        add_icon(icons_by_extension, "jsx", L'\ue7ba');             // ""
        add_icon(icons_by_extension, "key", L'\U000f0306');            // "󰌆"
        add_icon(icons_by_extension, "ksh", L'\uf489');             // ""
        add_icon(icons_by_extension, "kt", L'\ue634');              // ""
        add_icon(icons_by_extension, "kts", L'\ue634');             // ""
        add_icon(icons_by_extension, "kusto", L'\uf1c0');           // ""
        add_icon(icons_by_extension, "ldb", L'\uf1c0');             // ""
        add_icon(icons_by_extension, "ld", L'\ue624');              // ""
        add_icon(icons_by_extension, "less", L'\ue758');            // ""
        add_icon(icons_by_extension, "lhs", L'\ue777');             // ""
        add_icon(icons_by_extension, "license", L'\ue60a');         // ""
        add_icon(icons_by_extension, "lisp", L'\U000f0172');           // "󰅲"
        add_icon(icons_by_extension, "list", L'\uf03a');            // ""
        add_icon(icons_by_extension, "localized", L'\uf179');       // ""
        add_icon(icons_by_extension, "lock", L'\uf023');            // ""
        add_icon(icons_by_extension, "log", L'\uf18d');             // ""
        add_icon(icons_by_extension, "lss", L'\ue749');             // ""
        add_icon(icons_by_extension, "lua", L'\ue620');             // ""
        add_icon(icons_by_extension, "lz", L'\uf410');              // ""
        add_icon(icons_by_extension, "mgc", L'\uf0d0');             // ""
        add_icon(icons_by_extension, "m3u8", L'\U000f0411');           // "󰐑"
        add_icon(icons_by_extension, "m3u", L'\U000f0411');            // "󰐑"
        add_icon(icons_by_extension, "m4a", L'\uf001');             // ""
        add_icon(icons_by_extension, "m4v", L'\uf008');             // ""
        add_icon(icons_by_extension, "magnet", L'\uf076');          // ""
        add_icon(icons_by_extension, "malloy", L'\uf1c0');          // ""
        add_icon(icons_by_extension, "man", L'\uf02d');             // ""
        add_icon(icons_by_extension, "markdown", L'\ue609');        // ""
        add_icon(icons_by_extension, "md", L'\ue609');              // ""
        add_icon(icons_by_extension, "mjs", L'\ue74e');             // ""
        add_icon(icons_by_extension, "mkd", L'\ue609');             // ""
        add_icon(icons_by_extension, "mk", L'\uf085');              // ""
        add_icon(icons_by_extension, "mkv", L'\uf008');             // ""
        add_icon(icons_by_extension, "ml", L'\ue67a');              // ""
        add_icon(icons_by_extension, "mli", L'\ue67a');             // ""
        add_icon(icons_by_extension, "mll", L'\ue67a');             // ""
        add_icon(icons_by_extension, "mly", L'\ue67a');             // ""
        add_icon(icons_by_extension, "mobi", L'\ue28b');            // ""
        add_icon(icons_by_extension, "mov", L'\uf008');             // ""
        add_icon(icons_by_extension, "mp3", L'\uf001');             // ""
        add_icon(icons_by_extension, "mp4", L'\uf008');             // ""
        add_icon(icons_by_extension, "msi", L'\uf17a');             // ""
        add_icon(icons_by_extension, "mts", L'\ue628');             // ""
        add_icon(icons_by_extension, "mustache", L'\ue60f');        // ""
        add_icon(icons_by_extension, "nim", L'\ue677');             // ""
        add_icon(icons_by_extension, "nimble", L'\ue677');          // ""
        add_icon(icons_by_extension, "nix", L'\uf313');             // ""
        add_icon(icons_by_extension, "npmignore", L'\ue71e');       // ""
        add_icon(icons_by_extension, "odp", L'\uf1c4');             // ""
        add_icon(icons_by_extension, "ods", L'\uf1c3');             // ""
        add_icon(icons_by_extension, "odt", L'\uf1c2');             // ""
        add_icon(icons_by_extension, "ogg", L'\uf001');             // ""
        add_icon(icons_by_extension, "ogv", L'\uf008');             // ""
        add_icon(icons_by_extension, "old", L'\U000f006f');            // "󰁯"
        add_icon(icons_by_extension, "opus", L'\uf001');            // ""
        add_icon(icons_by_extension, "orig", L'\U000f006f');           // "󰁯"
        add_icon(icons_by_extension, "org", L'\ue633');             // ""
        add_icon(icons_by_extension, "otf", L'\uf031');             // ""
        add_icon(icons_by_extension, "o", L'\ueae8');               // ""
        add_icon(icons_by_extension, "part", L'\uf43a');            // ""
        add_icon(icons_by_extension, "patch", L'\ue728');           // ""
        add_icon(icons_by_extension, "pdb", L'\U000f0aaa');            // "󰪪"
        add_icon(icons_by_extension, "pdf", L'\uf1c1');             // ""
        add_icon(icons_by_extension, "pem", L'\U000f0306');            // "󰌆"
        add_icon(icons_by_extension, "phar", L'\ue608');            // ""
        add_icon(icons_by_extension, "php", L'\ue608');             // ""
        add_icon(icons_by_extension, "pkg", L'\uf187');             // ""
        add_icon(icons_by_extension, "pl", L'\ue67e');              // ""
        add_icon(icons_by_extension, "plist", L'\uf302');           // ""
        add_icon(icons_by_extension, "pls", L'\U000f0411');            // "󰐑"
        add_icon(icons_by_extension, "plx", L'\ue67e');             // ""
        add_icon(icons_by_extension, "pm", L'\ue67e');              // ""
        add_icon(icons_by_extension, "png", L'\uf1c5');             // ""
        add_icon(icons_by_extension, "pod", L'\ue67e');             // ""
        add_icon(icons_by_extension, "pp", L'\ue631');              // ""
        add_icon(icons_by_extension, "ppt", L'\uf1c4');             // ""
        add_icon(icons_by_extension, "pptx", L'\uf1c4');            // ""
        add_icon(icons_by_extension, "procfile", L'\ue21e');        // ""
        add_icon(icons_by_extension, "properties", L'\ue60b');      // ""
        add_icon(icons_by_extension, "prql", L'\uf1c0');            // ""
        add_icon(icons_by_extension, "ps1", L'\uf489');             // ""
        add_icon(icons_by_extension, "psd", L'\ue7b8');             // ""
        add_icon(icons_by_extension, "pub", L'\U000f0306');            // "󰌆"
        add_icon(icons_by_extension, "sbv", L'\U000f015e');            // "󰅞"
        add_icon(icons_by_extension, "scc", L'\U000f015e');            // "󰅞"
        add_icon(icons_by_extension, "slt", L'\U000f0221');            // "󰈡"
        add_icon(icons_by_extension, "smi", L'\U000f015e');            // "󰅞"
        add_icon(icons_by_extension, "pxm", L'\uf1c5');             // ""
        add_icon(icons_by_extension, "pyc", L'\ue606');             // ""
        add_icon(icons_by_extension, "py", L'\ue606');              // ""
        add_icon(icons_by_extension, "rakefile", L'\ue21e');        // ""
        add_icon(icons_by_extension, "rar", L'\uf410');             // ""
        add_icon(icons_by_extension, "razor", L'\uf1fa');           // ""
        add_icon(icons_by_extension, "rb", L'\ue21e');              // ""
        add_icon(icons_by_extension, "rdata", L'\U000f07d4');          // "󰟔"
        add_icon(icons_by_extension, "rdb", L'\ue76d');             // ""
        add_icon(icons_by_extension, "rdoc", L'\ue609');            // ""
        add_icon(icons_by_extension, "rds", L'\U000f07d4');            // "󰟔"
        add_icon(icons_by_extension, "readme", L'\ue609');          // ""
        add_icon(icons_by_extension, "rlib", L'\ue68b');            // ""
        add_icon(icons_by_extension, "rl", L'\uf11c');              // ""
        add_icon(icons_by_extension, "rmd", L'\ue609');             // ""
        add_icon(icons_by_extension, "rmeta", L'\ue68b');           // ""
        add_icon(icons_by_extension, "rpm", L'\uf187');             // ""
        add_icon(icons_by_extension, "rproj", L'\U000f05c6');          // "󰗆"
        add_icon(icons_by_extension, "rq", L'\uf1c0');              // ""
        add_icon(icons_by_extension, "rspec_parallel", L'\ue21e');  // ""
        add_icon(icons_by_extension, "rspec_status", L'\ue21e');    // ""
        add_icon(icons_by_extension, "rspec", L'\ue21e');           // ""
        add_icon(icons_by_extension, "rss", L'\uf09e');             // ""
        add_icon(icons_by_extension, "rs", L'\ue68b');              // ""
        add_icon(icons_by_extension, "rtf", L'\uf15c');             // ""
        add_icon(icons_by_extension, "rubydoc", L'\ue73b');         // ""
        add_icon(icons_by_extension, "r", L'\U000f07d4');              // "󰟔"
        add_icon(icons_by_extension, "ru", L'\ue21e');              // ""
        add_icon(icons_by_extension, "sass", L'\ue603');            // ""
        add_icon(icons_by_extension, "scala", L'\ue737');           // ""
        add_icon(icons_by_extension, "scpt", L'\uf302');            // ""
        add_icon(icons_by_extension, "scss", L'\ue603');            // ""
        add_icon(icons_by_extension, "shell", L'\uf489');           // ""
        add_icon(icons_by_extension, "sh", L'\uf489');              // ""
        add_icon(icons_by_extension, "sig", L'\ue60a');             // ""
        add_icon(icons_by_extension, "slim", L'\ue73b');            // ""
        add_icon(icons_by_extension, "sln", L'\ue70c');             // ""
        add_icon(icons_by_extension, "so", L'\ue624');              // ""
        add_icon(icons_by_extension, "sqlite3", L'\ue7c4');         // ""
        add_icon(icons_by_extension, "sql", L'\uf1c0');             // ""
        add_icon(icons_by_extension, "srt", L'\U000f0a16');            // "󰨖"
        add_icon(icons_by_extension, "styl", L'\ue600');            // ""
        add_icon(icons_by_extension, "stylus", L'\ue600');          // ""
        add_icon(icons_by_extension, "sublime-menu", L'\ue7aa');    // ""
        add_icon(icons_by_extension, "sublime-package", L'\ue7aa'); // ""
        add_icon(icons_by_extension, "sublime-project", L'\ue7aa'); // ""
        add_icon(icons_by_extension, "sublime-session", L'\ue7aa'); // ""
        add_icon(icons_by_extension, "sub", L'\U000f0a16');            // "󰨖"
        add_icon(icons_by_extension, "s", L'\uf471');               // ""
        add_icon(icons_by_extension, "svg", L'\uf1c5');             // ""
        add_icon(icons_by_extension, "svelte", L'\ue697');          // ""
        add_icon(icons_by_extension, "swift", L'\ue755');           // ""
        add_icon(icons_by_extension, "swp", L'\ue62b');             // ""
        add_icon(icons_by_extension, "sym", L'\ueae8');             // ""
        add_icon(icons_by_extension, "tar", L'\uf410');             // ""
        add_icon(icons_by_extension, "taz", L'\uf410');             // ""
        add_icon(icons_by_extension, "tbz", L'\uf410');             // ""
        add_icon(icons_by_extension, "tbz2", L'\uf410');            // ""
        add_icon(icons_by_extension, "tex", L'\ue600');             // ""
        add_icon(icons_by_extension, "tgz", L'\uf410');             // ""
        add_icon(icons_by_extension, "tiff", L'\uf1c5');            // ""
        add_icon(icons_by_extension, "timestamp", L'\uf43a');       // ""
        add_icon(icons_by_extension, "toml", L'\ue60b');            // ""
        add_icon(icons_by_extension, "torrent", L'\U000f048d');        // "󰒍"
        add_icon(icons_by_extension, "trash", L'\uf1f8');           // ""
        add_icon(icons_by_extension, "ts", L'\ue628');              // ""
        add_icon(icons_by_extension, "tsx", L'\ue7ba');             // ""
        add_icon(icons_by_extension, "ttc", L'\uf031');             // ""
        add_icon(icons_by_extension, "ttf", L'\uf031');             // ""
        add_icon(icons_by_extension, "t", L'\ue769');               // ""
        add_icon(icons_by_extension, "twig", L'\ue61c');            // ""
        add_icon(icons_by_extension, "txt", L'\uf15c');             // ""
        add_icon(icons_by_extension, "unity", L'\ue721');           // ""
        add_icon(icons_by_extension, "unity32", L'\ue721');         // ""
        add_icon(icons_by_extension, "video", L'\uf008');           // ""
        add_icon(icons_by_extension, "vim", L'\ue62b');             // ""
        add_icon(icons_by_extension, "vlc", L'\U000f0411');            // "󰐑"
        add_icon(icons_by_extension, "vtt", L'\U000f015e');            // "󰅞"
        add_icon(icons_by_extension, "vue", L'\U000f0844');            // "󰡄"
        add_icon(icons_by_extension, "wav", L'\uf001');             // ""
        add_icon(icons_by_extension, "webm", L'\uf008');            // ""
        add_icon(icons_by_extension, "webp", L'\uf1c5');            // ""
        add_icon(icons_by_extension, "whl", L'\uf487');             // ""
        add_icon(icons_by_extension, "windows", L'\uf17a');         // ""
        add_icon(icons_by_extension, "wma", L'\uf001');             // ""
        add_icon(icons_by_extension, "wmv", L'\uf008');             // ""
        add_icon(icons_by_extension, "woff2", L'\uf031');           // ""
        add_icon(icons_by_extension, "woff", L'\uf031');            // ""
        add_icon(icons_by_extension, "wpl", L'\U000f0411');            // "󰐑"
        add_icon(icons_by_extension, "xbps", L'\uf187');            // ""
        add_icon(icons_by_extension, "xcf", L'\uf1c5');             // ""
        add_icon(icons_by_extension, "xls", L'\uf1c3');             // ""
        add_icon(icons_by_extension, "xlsx", L'\uf1c3');            // ""
        add_icon(icons_by_extension, "xml", L'\uf121');             // ""
        add_icon(icons_by_extension, "xul", L'\uf269');             // ""
        add_icon(icons_by_extension, "xz", L'\uf410');              // ""
        add_icon(icons_by_extension, "yaml", L'\ue60b');            // ""
        add_icon(icons_by_extension, "yml", L'\ue60b');             // ""
        add_icon(icons_by_extension, "zip", L'\uf410');             // ""
        add_icon(icons_by_extension, "zig", L'\ue6a9');             // ""
        add_icon(icons_by_extension, "zon", L'\ue60b');             // ""
        add_icon(icons_by_extension, "zshrc", L'\uf489');           // ""
        add_icon(icons_by_extension, "zsh-theme", L'\uf489');       // ""
        add_icon(icons_by_extension, "zsh", L'\uf489');             // ""
        add_icon(icons_by_extension, "zst", L'\uf410');             // ""
}

void init_icon_by_name_map() {
  
        add_icon(icons_by_name, "a.out",                  L'\uf489');            // ""
        add_icon(icons_by_name, "api",                    L'\U000f048d');        // "󰒍"
        add_icon(icons_by_name, ".asoundrc",              L'\ue615');            // ""
        add_icon(icons_by_name, ".atom",                  L'\ue764');            // ""
        add_icon(icons_by_name, ".ash",                   L'\uf489');            // ""
        add_icon(icons_by_name, ".ash_history",           L'\uf489');            // ""
        add_icon(icons_by_name, "authorized_keys",        L'\ue60a');            // ""
        add_icon(icons_by_name, "assets",                 L'\uf0c7');            // ""
        add_icon(icons_by_name, ".android",               L'\uf17b');            // ""
        add_icon(icons_by_name, ".audacity-data",         L'\ue5fc');            // ""
        add_icon(icons_by_name, "backups",                L'\U000f006f');        // "󰁯"
        add_icon(icons_by_name, ".bash_history",          L'\U000f1183');        // "󱆃"
        add_icon(icons_by_name, ".bash_logout",           L'\U000f1183');        // "󱆃"
        add_icon(icons_by_name, ".bash_profile",          L'\U000f1183');        // "󱆃"
        add_icon(icons_by_name, ".bashrc",                L'\U000f1183');        // "󱆃"
        add_icon(icons_by_name, "bin",                    L'\ue5fc');            // ""
        add_icon(icons_by_name, ".bpython_history",       L'\ue606');            // ""
        add_icon(icons_by_name, "build",                  L'\uf487');            // ""
        add_icon(icons_by_name, "bspwmrc",                L'\ue615');            // ""
        add_icon(icons_by_name, "build.ninja",            L'\uf0ad');            // ""
        add_icon(icons_by_name, ".cache",                 L'\U000f00e8');        // "󰃨"
        add_icon(icons_by_name, "cache",                  L'\U000f00e8');        // "󰃨"
        add_icon(icons_by_name, "cargo.lock",             L'\ue68b');            // ""
        add_icon(icons_by_name, "cargo.toml",             L'\ue68b');            // ""
        add_icon(icons_by_name, ".cargo",                 L'\ue68b');            // ""
        add_icon(icons_by_name, ".ccls-cache",            L'\U000f00e8');        // "󰃨"
        add_icon(icons_by_name, "changelog",              L'\ue609');            // ""
        add_icon(icons_by_name, ".clang-format",          L'\ue615');            // ""
        add_icon(icons_by_name, "composer.json",          L'\ue608');            // ""
        add_icon(icons_by_name, "composer.lock",          L'\ue608');            // ""
        add_icon(icons_by_name, "conf.d",                 L'\ue5fc');            // ""
        add_icon(icons_by_name, "config.ac",              L'\ue615');            // ""
        add_icon(icons_by_name, "config.el",              L'\ue632');            // ""
        add_icon(icons_by_name, "config.mk",              L'\ue615');            // ""
        add_icon(icons_by_name, ".config",                L'\ue5fc');            // ""
        add_icon(icons_by_name, "config",                 L'\ue5fc');            // ""
        add_icon(icons_by_name, "configure",              L'\uf0ad');            // ""
        add_icon(icons_by_name, "content",                L'\uf0c7');            // ""
        add_icon(icons_by_name, "contributing",           L'\ue60a');            // ""
        add_icon(icons_by_name, "copyright",              L'\ue60a');            // ""
        add_icon(icons_by_name, "cron.daily",             L'\ue5fc');            // ""
        add_icon(icons_by_name, "cron.d",                 L'\ue5fc');            // ""
        add_icon(icons_by_name, "cron.deny",              L'\ue615');            // ""
        add_icon(icons_by_name, "cron.hourly",            L'\ue5fc');            // ""
        add_icon(icons_by_name, "cron.monthly",           L'\ue5fc');            // ""
        add_icon(icons_by_name, "crontab",                L'\ue615');            // ""
        add_icon(icons_by_name, "cron.weekly",            L'\ue5fc');            // ""
        add_icon(icons_by_name, "crypttab",               L'\ue615');            // ""
        add_icon(icons_by_name, ".cshrc",                 L'\U000f1183');        // "󱆃"
        add_icon(icons_by_name, "csh.cshrc",              L'\U000f1183');        // "󱆃"
        add_icon(icons_by_name, "csh.login",              L'\U000f1183');        // "󱆃"
        add_icon(icons_by_name, "csh.logout",             L'\U000f1183');        // "󱆃"
        add_icon(icons_by_name, "css",                    L'\ue749');            // ""
        add_icon(icons_by_name, "custom.el",              L'\ue632');            // ""
        add_icon(icons_by_name, ".dbus",                  L'\uf013');            // ""
        add_icon(icons_by_name, "desktop",                L'\uf108');            // ""
        add_icon(icons_by_name, "docker-compose.yml",     L'\uf308');            // ""
        add_icon(icons_by_name, "dockerfile",             L'\uf308');            // ""
        add_icon(icons_by_name, "doc",                    L'\uf02d');            // ""
        add_icon(icons_by_name, "dist",                   L'\uf487');            // ""
        add_icon(icons_by_name, "documents",              L'\uf02d');            // ""
        add_icon(icons_by_name, ".doom.d",                L'\ue632');            // ""
        add_icon(icons_by_name, "downloads",              L'\U000f024d');        // "󰉍"
        add_icon(icons_by_name, ".ds_store",              L'\uf179');            // ""
        add_icon(icons_by_name, ".editorconfig",          L'\ue615');            // ""
        add_icon(icons_by_name, ".electron-gyp",          L'\ue5fa');            // ""
        add_icon(icons_by_name, ".emacs.d",               L'\ue632');            // ""
        add_icon(icons_by_name, ".env",                   L'\uf462');            // ""
        add_icon(icons_by_name, "environment",            L'\uf462');            // ""
        add_icon(icons_by_name, ".eslintrc.json",         L'\uf462');            // ""
        add_icon(icons_by_name, ".eslintrc.js",           L'\uf462');            // ""
        add_icon(icons_by_name, ".eslintrc.yml",          L'\uf462');            // ""
        add_icon(icons_by_name, "etc",                    L'\ue5fc');            // ""
        add_icon(icons_by_name, "favicon.ico",            L'\uf005');            // ""
        add_icon(icons_by_name, "favicons",               L'\uf005');            // ""
        add_icon(icons_by_name, ".fennelrc",              L'\ue615');            // ""
        add_icon(icons_by_name, "fstab",                  L'\uf1c0');            // ""
        add_icon(icons_by_name, ".fastboot",              L'\uf17b');            // ""
        add_icon(icons_by_name, ".gitattributes",         L'\uf1d3');            // ""
        add_icon(icons_by_name, ".gitconfig",             L'\uf1d3');            // ""
        add_icon(icons_by_name, ".git-credentials",       L'\ue60a');            // ""
        add_icon(icons_by_name, ".github",                L'\ue5fd');            // ""
        add_icon(icons_by_name, "gitignore_global",       L'\uf1d3');            // ""
        add_icon(icons_by_name, ".gitignore",             L'\uf1d3');            // ""
        add_icon(icons_by_name, ".gitlab-ci.yml",         L'\uf296');            // ""
        add_icon(icons_by_name, ".gitmodules",            L'\uf1d3');            // ""
        add_icon(icons_by_name, ".git",                   L'\ue5fb');            // ""
        add_icon(icons_by_name, ".gnupg",                 L'\U000f08ac');        // "󰢬"
        add_icon(icons_by_name, "go.mod",                 L'\ue627');            // ""
        add_icon(icons_by_name, "go.sum",                 L'\ue627');            // ""
        add_icon(icons_by_name, "go.work",                L'\ue627');            // ""
        add_icon(icons_by_name, "gradle",                 L'\ue660');            // ""
        add_icon(icons_by_name, "gradle.properties",      L'\ue660');            // ""
        add_icon(icons_by_name, "gradlew",                L'\ue660');            // ""
        add_icon(icons_by_name, "gradlew.bat",            L'\ue660');            // ""
        add_icon(icons_by_name, "group",                  L'\ue615');            // ""
        add_icon(icons_by_name, "gruntfile.coffee",       L'\ue611');            // ""
        add_icon(icons_by_name, "gruntfile.js",           L'\ue611');            // ""
        add_icon(icons_by_name, "gruntfile.ls",           L'\ue611');            // ""
        add_icon(icons_by_name, "gshadow",                L'\ue615');            // ""
        add_icon(icons_by_name, "gulpfile.coffee",        L'\ue610');            // ""
        add_icon(icons_by_name, "gulpfile.js",            L'\ue610');            // ""
        add_icon(icons_by_name, "gulpfile.ls",            L'\ue610');            // ""
        add_icon(icons_by_name, "heroku.yml",             L'\ue77b');            // ""
        add_icon(icons_by_name, "hidden",                 L'\uf023');            // ""
        add_icon(icons_by_name, "home",                   L'\uf015');            // ""
        add_icon(icons_by_name, "hostname",               L'\ue615');            // ""
        add_icon(icons_by_name, "hosts",                  L'\U000f0002');        // "󰀂"
        add_icon(icons_by_name, ".htaccess",              L'\ue615');            // ""
        add_icon(icons_by_name, "htoprc",                 L'\ue615');            // ""
        add_icon(icons_by_name, ".htpasswd",              L'\ue615');            // ""
        add_icon(icons_by_name, ".icons",                 L'\uf005');            // ""
        add_icon(icons_by_name, "icons",                  L'\uf005');            // ""
        add_icon(icons_by_name, "id_dsa",                 L'\U000f0dd6');        // "󰷖"
        add_icon(icons_by_name, "id_ecdsa",               L'\U000f0dd6');        // "󰷖"
        add_icon(icons_by_name, "id_rsa",                 L'\U000f0dd6');        // "󰷖"
        add_icon(icons_by_name, ".idlerc",                L'\ue235');            // ""
        add_icon(icons_by_name, "img",                    L'\uf1c5');            // ""
        add_icon(icons_by_name, "include",                L'\ue5fc');            // ""
        add_icon(icons_by_name, "init.el",                L'\ue632');            // ""
        add_icon(icons_by_name, ".inputrc",               L'\ue615');            // ""
        add_icon(icons_by_name, "inputrc",                L'\ue615');            // ""
        add_icon(icons_by_name, ".java",                  L'\ue256');            // ""
        add_icon(icons_by_name, "jenkinsfile",            L'\ue66e');            // ""
        add_icon(icons_by_name, "js",                     L'\ue74e');            // ""
        add_icon(icons_by_name, ".jupyter",               L'\ue606');            // ""
        add_icon(icons_by_name, "kbuild",                 L'\ue615');            // ""
        add_icon(icons_by_name, "kconfig",                L'\ue615');            // ""
        add_icon(icons_by_name, "kdeglobals",             L'\ue615');            // ""
        add_icon(icons_by_name, "kdenliverc",             L'\ue615');            // ""
        add_icon(icons_by_name, "known_hosts",            L'\ue60a');            // ""
        add_icon(icons_by_name, ".kshrc",                 L'\uf489');            // ""
        add_icon(icons_by_name, "libexec",                L'\uf121');            // ""
        add_icon(icons_by_name, "lib32",                  L'\uf121');            // ""
        add_icon(icons_by_name, "lib64",                  L'\uf121');            // ""
        add_icon(icons_by_name, "lib",                    L'\uf121');            // ""
        add_icon(icons_by_name, "license.md",             L'\ue60a');            // ""
        add_icon(icons_by_name, "licenses",               L'\ue60a');            // ""
        add_icon(icons_by_name, "license.txt",            L'\ue60a');            // ""
        add_icon(icons_by_name, "license",                L'\ue60a');            // ""
        add_icon(icons_by_name, "localized",              L'\uf179');            // ""
        add_icon(icons_by_name, "lsb-release",            L'\ue615');            // ""
        add_icon(icons_by_name, ".lynxrc",                L'\ue615');            // ""
        add_icon(icons_by_name, ".mailcap",               L'\U000f01f0');        // "󰇰"
        add_icon(icons_by_name, "mail",                   L'\U000f01f0');        // "󰇰"
        add_icon(icons_by_name, "magic",                  L'\uf0d0');            // ""
        add_icon(icons_by_name, "maintainers",            L'\ue60a');            // ""
        add_icon(icons_by_name, "makefile.ac",            L'\ue615');            // ""
        add_icon(icons_by_name, "makefile",               L'\ue615');            // ""
        add_icon(icons_by_name, "manifest",               L'\uf292');            // ""
        add_icon(icons_by_name, "md5sum",                 L'\U000f0565');        // "󰕥"
        add_icon(icons_by_name, "meson.build",            L'\uf0ad');            // ""
        add_icon(icons_by_name, "metadata",               L'\ue5fc');            // ""
        add_icon(icons_by_name, "metadata.xml",           L'\uf462');            // ""
        add_icon(icons_by_name, "media",                  L'\uf40f');            // ""
        add_icon(icons_by_name, ".mime.types",            L'\U000f0645');        // "󰙅"
        add_icon(icons_by_name, "mime.types",             L'\U000f0645');        // "󰙅"
        add_icon(icons_by_name, "module.symvers",         L'\uf471');            // ""
        add_icon(icons_by_name, ".mozilla",               L'\ue786');            // ""
        add_icon(icons_by_name, "music",                  L'\U000f1359');        // "󱍙"
        add_icon(icons_by_name, "muttrc",                 L'\ue615');            // ""
        add_icon(icons_by_name, ".muttrc",                L'\ue615');            // ""
        add_icon(icons_by_name, ".mutt",                  L'\ue615');            // ""
        add_icon(icons_by_name, ".mypy_cache",            L'\U000f00e8');        // "󰃨"
        add_icon(icons_by_name, "neomuttrc",              L'\ue615');            // ""
        add_icon(icons_by_name, ".neomuttrc",             L'\ue615');            // ""
        add_icon(icons_by_name, "netlify.toml",           L'\uf233');            // ""
        add_icon(icons_by_name, ".nix-channels",          L'\uf313');            // ""
        add_icon(icons_by_name, ".nix-defexpr",           L'\uf313');            // ""
        add_icon(icons_by_name, ".node-gyp",              L'\ue5fa');            // ""
        add_icon(icons_by_name, "node_modules",           L'\ue5fa');            // ""
        add_icon(icons_by_name, ".node_repl_history",     L'\ue718');            // ""
        add_icon(icons_by_name, "npmignore",              L'\ue71e');            // ""
        add_icon(icons_by_name, ".npm",                   L'\ue5fa');            // ""
        add_icon(icons_by_name, "nvim",                   L'\uf36f');            // ""
        add_icon(icons_by_name, "obj",                    L'\ue624');            // ""
        add_icon(icons_by_name, "os-release",             L'\ue615');            // ""
        add_icon(icons_by_name, "package.json",           L'\ue718');            // ""
        add_icon(icons_by_name, "package-lock.json",      L'\ue718');            // ""
        add_icon(icons_by_name, "packages.el",            L'\ue632');            // ""
        add_icon(icons_by_name, "pam.d",                  L'\U000f08ac');        // "󰢬"
        add_icon(icons_by_name, "passwd",                 L'\uf023');            // ""
        add_icon(icons_by_name, "pictures",               L'\U000f024f');        // "󰉏"
        add_icon(icons_by_name, "pkgbuild",               L'\uf303');            // ""
        add_icon(icons_by_name, ".pki",                   L'\uf023');            // ""
        add_icon(icons_by_name, "portage",                L'\uf30d');            // ""
        add_icon(icons_by_name, "profile",                L'\ue615');            // ""
        add_icon(icons_by_name, ".profile",               L'\ue615');            // ""
        add_icon(icons_by_name, "public",                 L'\uf415');            // ""
        add_icon(icons_by_name, "__pycache__",            L'\ue606');            // ""
        add_icon(icons_by_name, "pyproject.toml",         L'\ue606');            // ""
        add_icon(icons_by_name, ".python_history",        L'\ue606');            // ""
        add_icon(icons_by_name, ".pypirc",                L'\ue606');            // ""
        add_icon(icons_by_name, "rc.lua",                 L'\ue615');            // ""
        add_icon(icons_by_name, "readme",                 L'\ue609');            // ""
        add_icon(icons_by_name, ".release.toml",          L'\ue68b');            // ""
        add_icon(icons_by_name, "requirements.txt",       L'\U000f0320');        // "󰌠"
        add_icon(icons_by_name, "robots.txt",             L'\U000f06a9');        // "󰚩"
        add_icon(icons_by_name, "root",                   L'\U000f0250');        // "󰉐"
        add_icon(icons_by_name, "rubydoc",                L'\ue73b');            // ""
        add_icon(icons_by_name, "runtime.txt",            L'\U000f0320');        // "󰌠"
        add_icon(icons_by_name, ".rustup",                L'\ue68b');            // ""
        add_icon(icons_by_name, "rustfmt.toml",           L'\ue68b');            // ""
        add_icon(icons_by_name, ".rvm",                   L'\ue21e');            // ""
        add_icon(icons_by_name, "sass",                   L'\ue603');            // ""
        add_icon(icons_by_name, "sbin",                   L'\ue5fc');            // ""
        add_icon(icons_by_name, "scripts",                L'\uf489');            // ""
        add_icon(icons_by_name, "scss",                   L'\ue603');            // ""
        add_icon(icons_by_name, "sha256sum",              L'\U000f0565');        // "󰕥"
        add_icon(icons_by_name, "shadow",                 L'\ue615');            // ""
        add_icon(icons_by_name, "share",                  L'\uf064');            // ""
        add_icon(icons_by_name, ".shellcheckrc",          L'\ue615');            // ""
        add_icon(icons_by_name, "shells",                 L'\ue615');            // ""
        add_icon(icons_by_name, ".spacemacs",             L'\ue632');            // ""
        add_icon(icons_by_name, ".sqlite_history",        L'\ue7c4');            // ""
        add_icon(icons_by_name, "src",                    L'\U000f19fc');        // "󱧼"
        add_icon(icons_by_name, ".ssh",                   L'\U000f08ac');        // "󰢬"
        add_icon(icons_by_name, "static",                 L'\uf0c7');            // ""
        add_icon(icons_by_name, "std",                    L'\U000f0171');        // "󰅱"
        add_icon(icons_by_name, "styles",                 L'\ue749');            // ""
        add_icon(icons_by_name, "subgid",                 L'\ue615');            // ""
        add_icon(icons_by_name, "subuid",                 L'\ue615');            // ""
        add_icon(icons_by_name, "sudoers",                L'\uf023');            // ""
        add_icon(icons_by_name, "sxhkdrc",                L'\ue615');            // ""
        add_icon(icons_by_name, "template",               L'\uf32e');            // ""
        add_icon(icons_by_name, "tests",                  L'\U000f0668');        // "󰙨"
        add_icon(icons_by_name, "tigrc",                  L'\ue615');            // ""
        add_icon(icons_by_name, "timezone",               L'\uf43a');            // ""
        add_icon(icons_by_name, "tox.ini",                L'\ue615');            // ""
        add_icon(icons_by_name, ".trash",                 L'\uf1f8');            // ""
        add_icon(icons_by_name, "ts",                     L'\ue628');            // ""
        add_icon(icons_by_name, ".tox",                   L'\ue606');            // ""
        add_icon(icons_by_name, "unlicense",              L'\ue60a');            // ""
        add_icon(icons_by_name, "url",                    L'\uf0ac');            // ""
        add_icon(icons_by_name, "user-dirs.dirs",         L'\ue5fc');            // ""
        add_icon(icons_by_name, "vagrantfile",            L'\ue615');            // ""
        add_icon(icons_by_name, "vendor",                 L'\U000f0ae6');        // "󰫦"
        add_icon(icons_by_name, "venv",                   L'\U000f0320');        // "󰌠"
        add_icon(icons_by_name, "videos",                 L'\uf03d');            // ""
        add_icon(icons_by_name, ".viminfo",               L'\ue62b');            // ""
        add_icon(icons_by_name, ".vimrc",                 L'\ue62b');            // ""
        add_icon(icons_by_name, "vimrc",                  L'\ue62b');            // ""
        add_icon(icons_by_name, ".vim",                   L'\ue62b');            // ""
        add_icon(icons_by_name, "vim",                    L'\ue62b');            // ""
        add_icon(icons_by_name, ".vscode",                L'\ue70c');            // ""
        add_icon(icons_by_name, "webpack.config.js",      L'\U000f072b');        // "󰜫"
        add_icon(icons_by_name, ".wgetrc",                L'\ue615');            // ""
        add_icon(icons_by_name, "wgetrc",                 L'\ue615');            // ""
        add_icon(icons_by_name, ".xauthority",            L'\ue615');            // ""
        add_icon(icons_by_name, ".Xauthority",            L'\ue615');            // ""
        add_icon(icons_by_name, "xbps.d",                 L'\uf32e');            // ""
        add_icon(icons_by_name, "xbps-src",               L'\uf32e');            // ""
        add_icon(icons_by_name, ".xinitrc",               L'\ue615');            // ""
        add_icon(icons_by_name, ".xmodmap",               L'\ue615');            // ""
        add_icon(icons_by_name, ".Xmodmap",               L'\ue615');            // ""
        add_icon(icons_by_name, "xmonad.hs",              L'\ue615');            // ""
        add_icon(icons_by_name, "xorg.conf.d",            L'\ue5fc');            // ""
        add_icon(icons_by_name, ".xprofile",              L'\ue615');            // ""
        add_icon(icons_by_name, ".Xprofile",              L'\ue615');            // ""
        add_icon(icons_by_name, ".xresources",            L'\ue615');            // ""
        add_icon(icons_by_name, ".yarnrc",                L'\ue6a7');            // ""
        add_icon(icons_by_name, "yarn.lock",              L'\ue6a7');            // ""
        add_icon(icons_by_name, "zathurarc",              L'\ue615');            // ""
        add_icon(icons_by_name, ".zcompdump",             L'\ue615');            // ""
        add_icon(icons_by_name, ".zlogin",                L'\U000f1183');        // "󱆃"
        add_icon(icons_by_name, ".zlogout",               L'\U000f1183');        // "󱆃"
        add_icon(icons_by_name, ".zprofile",              L'\U000f1183');        // "󱆃"
        add_icon(icons_by_name, ".zsh_history",           L'\U000f1183');        // "󱆃"
        add_icon(icons_by_name, ".zshrc",                 L'\U000f1183');        // "󱆃"
}


